-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Brainlette.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Brainlette.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Brainlette.Abs.Ident -> Result
transIdent x = case x of
  Brainlette.Abs.Ident string -> failure x

transProg :: Show a => Brainlette.Abs.Prog' a -> Result
transProg x = case x of
  Brainlette.Abs.Program _ topdefs -> failure x

transTopDef :: Show a => Brainlette.Abs.TopDef' a -> Result
transTopDef x = case x of
  Brainlette.Abs.FnDef _ type_ ident args blk -> failure x

transArg :: Show a => Brainlette.Abs.Arg' a -> Result
transArg x = case x of
  Brainlette.Abs.Argument _ type_ ident -> failure x

transBlk :: Show a => Brainlette.Abs.Blk' a -> Result
transBlk x = case x of
  Brainlette.Abs.Block _ stmts -> failure x

transItem :: Show a => Brainlette.Abs.Item' a -> Result
transItem x = case x of
  Brainlette.Abs.NoInit _ ident -> failure x
  Brainlette.Abs.Init _ ident expr -> failure x

transStmt :: Show a => Brainlette.Abs.Stmt' a -> Result
transStmt x = case x of
  Brainlette.Abs.Empty _ -> failure x
  Brainlette.Abs.BStmt _ blk -> failure x
  Brainlette.Abs.Decl _ type_ items -> failure x
  Brainlette.Abs.Ass _ ident expr -> failure x
  Brainlette.Abs.Incr _ ident -> failure x
  Brainlette.Abs.Decr _ ident -> failure x
  Brainlette.Abs.Ret _ expr -> failure x
  Brainlette.Abs.VRet _ -> failure x
  Brainlette.Abs.Cond _ expr stmt -> failure x
  Brainlette.Abs.CondElse _ expr stmt1 stmt2 -> failure x
  Brainlette.Abs.While _ expr stmt -> failure x
  Brainlette.Abs.SExp _ expr -> failure x

transType :: Show a => Brainlette.Abs.Type' a -> Result
transType x = case x of
  Brainlette.Abs.Int _ -> failure x
  Brainlette.Abs.Doub _ -> failure x
  Brainlette.Abs.Bool _ -> failure x
  Brainlette.Abs.Void _ -> failure x
  Brainlette.Abs.Fun _ type_ types -> failure x

transExpr :: Show a => Brainlette.Abs.Expr' a -> Result
transExpr x = case x of
  Brainlette.Abs.EVar _ ident -> failure x
  Brainlette.Abs.ELitInt _ integer -> failure x
  Brainlette.Abs.ELitDoub _ double -> failure x
  Brainlette.Abs.ELitTrue _ -> failure x
  Brainlette.Abs.ELitFalse _ -> failure x
  Brainlette.Abs.EApp _ ident exprs -> failure x
  Brainlette.Abs.EString _ string -> failure x
  Brainlette.Abs.Neg _ expr -> failure x
  Brainlette.Abs.Not _ expr -> failure x
  Brainlette.Abs.EMul _ expr1 mulop expr2 -> failure x
  Brainlette.Abs.EAdd _ expr1 addop expr2 -> failure x
  Brainlette.Abs.ERel _ expr1 relop expr2 -> failure x
  Brainlette.Abs.EAnd _ expr1 expr2 -> failure x
  Brainlette.Abs.EOr _ expr1 expr2 -> failure x

transAddOp :: Show a => Brainlette.Abs.AddOp' a -> Result
transAddOp x = case x of
  Brainlette.Abs.Plus _ -> failure x
  Brainlette.Abs.Minus _ -> failure x

transMulOp :: Show a => Brainlette.Abs.MulOp' a -> Result
transMulOp x = case x of
  Brainlette.Abs.Times _ -> failure x
  Brainlette.Abs.Div _ -> failure x
  Brainlette.Abs.Mod _ -> failure x

transRelOp :: Show a => Brainlette.Abs.RelOp' a -> Result
transRelOp x = case x of
  Brainlette.Abs.LTH _ -> failure x
  Brainlette.Abs.LE _ -> failure x
  Brainlette.Abs.GTH _ -> failure x
  Brainlette.Abs.GE _ -> failure x
  Brainlette.Abs.EQU _ -> failure x
  Brainlette.Abs.NE _ -> failure x
